version: 2
updates:
  # GitHub Actions monitoring
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    labels:
      - "ci"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
